"""empty message

Revision ID: 1405407d974f
Revises: 
Create Date: 2023-02-24 21:01:13.246143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1405407d974f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_category', sa.String(), nullable=True),
    sa.Column('service_type_name', sa.String(), nullable=True),
    sa.Column('opened', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_type_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_phone_number', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('reg_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_phone_number')
    )
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('card_number', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('card_name', sa.String(), nullable=True),
    sa.Column('exp_date', sa.Date(), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('card_number'),
    sa.UniqueConstraint('card_number'),
    sa.UniqueConstraint('id')
    )
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=55), nullable=True),
    sa.Column('business_card', sa.Integer(), nullable=True),
    sa.Column('service_type', sa.String(), nullable=True),
    sa.Column('opened', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_card'], ['cards.card_number'], ),
    sa.ForeignKeyConstraint(['service_type'], ['services.service_type_name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('p2p',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_from_card', sa.Integer(), nullable=True),
    sa.Column('user_to_card', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('p2p_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_from_card'], ['cards.card_number'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_number', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('payment_type', sa.String(), nullable=True),
    sa.Column('pay_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_number'], ['cards.card_number'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_type'], ['services.service_type_name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('p2p')
    op.drop_table('businesses')
    op.drop_table('cards')
    op.drop_table('users')
    op.drop_table('services')
    # ### end Alembic commands ###
